# Generated by Django 2.2.5 on 2020-05-31 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('loginmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Employee.LoginModel')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.IntegerField(max_length=1)),
                ('date_of_joining', models.DateField()),
                ('retirement_date', models.DateField()),
                ('user_img', models.CharField(max_length=1000)),
            ],
            bases=('Employee.loginmodel',),
        ),
    ]
