# Generated by Django 2.2.5 on 2020-05-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
