# Generated by Django 2.2.5 on 2020-05-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20200531_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='admin_num',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
