# Generated by Django 2.2.5 on 2020-06-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20200610_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='../static/Employee/images'),
        ),
    ]
