# Generated by Django 2.2.5 on 2020-06-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20200612_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
