# Generated by Django 2.2.5 on 2020-06-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20200615_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='retirement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
