# Generated by Django 2.2.5 on 2020-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_auto_20200616_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='gender',
            field=models.IntegerField(choices=[(0, '男性'), (1, '女性')], default=0),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='Employee/static/Employee/images'),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
